### ISSUE TITLE
nim install nexus is throwing a warning that says that the package has an incorrect structure

### ISSUE THREAD

**Issue by basilrwx** [jfilby/nexus#39]
System OS: Debian 12
Processor: AMD Ryzen 5

![image](https://github.com/jfilby/nexus/assets/67640495/25b22853-cbc7-4e1c-8e65-47c302617d87)

**Comment by jfilby** [comment]
This isn't high priority for me as its just a warning. But thanks for logging this, I'll take a look when I get time. PRs are welcome.

**Comment by jfilby** [comment]
This should be corrected in [v0.1.4.8](https://github.com/jfilby/nexus/tree/v0.1.4.8).
